### ISSUE TITLE
uncaught errors in requirejs mode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#41]
Noted with test-server, in requirejs mode with fuzzTest.

This one is identical to https://github.com/phetsims/balancing-chemical-equations/issues/109:
```js
Uncaught Error: Assertion failed: during disposal, expected 0 observers, actual = 1
Error: Assertion failed: during disposal, expected 0 observers, actual = 1
    at window.assertions.assertFunction (http://localhost/~cmalley/Github/assert/js/assert.js:22:13)
    at DerivedProperty.Property.disposeProperty (http://localhost/~cmalley/Github/axon/js/Property.js?bust=1447655437197:54:17)
    at DerivedProperty.inherit.dispose (http://localhost/~cmalley/Github/axon/js/Property.js?bust=1447655437197:310:14)
    at DerivedProperty.inherit.dispose (http://localhost/~cmalley/Github/axon/js/DerivedProperty.js?bust=1447655437197:60:34)
    at ChallengeNode.inherit.dispose (http://localhost/~cmalley/Github/reactants-products-and-leftovers/js/game/view/ChallengeNode.js?bust=1447655437197:347:39)
    at PlayNode.inherit.step (http://localhost/~cmalley/Github/reactants-products-and-leftovers/js/game/view/PlayNode.js?bust=1447655437197:152:34)
    at GameView.inherit.step (http://localhost/~cmalley/Github/reactants-products-and-leftovers/js/game/view/GameView.js?bust=1447655437197:86:23)
    at Sim.inherit.stepSimulation (http://localhost/~cmalley/Github/joist/js/Sim.js?bust=1447655437197:815:25)
    at Sim.inherit.runAnimationLoop (http://localhost/~cmalley/Github/joist/js/Sim.js?bust=1447655437197:750:12)
```

This one occurs a dozen or so times:

```
Uncaught Error: Assertion failed: Attempted to removeChild with a node that was not a child.
Error: Assertion failed: Attempted to removeChild with a node that was not a child.
    at window.assertions.assertFunction (http://localhost/~cmalley/Github/assert/js/assert.js:22:13)
    at PlayNode.extend.removeChild (http://localhost/~cmalley/Github/scenery/js/nodes/Node.js?bust=1447655437197:373:17)
    at PlayNode.inherit.step (http://localhost/~cmalley/Github/reactants-products-and-leftovers/js/game/view/PlayNode.js?bust=1447655437197:151:16)
    at GameView.inherit.step (http://localhost/~cmalley/Github/reactants-products-and-leftovers/js/game/view/GameView.js?bust=1447655437197:86:23)
    at Sim.inherit.stepSimulation (http://localhost/~cmalley/Github/joist/js/Sim.js?bust=1447655437197:815:25)
    at Sim.inherit.runAnimationLoop (http://localhost/~cmalley/Github/joist/js/Sim.js?bust=1447655437197:750:12)
```

**Comment by pixelzoom** [comment]
The second error (`Attempted to removeChild`) was apparently a result of the first error (`Assertion failed: during disposal,`).  Fixing the first error resolved the second, as tested with `?ea&fuzzMouse&screens=3`.

Closing.
