### ISSUE TITLE
CT: shuffleListeners test is failing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#85]
Failing intermittently in CT. Started failing 3/20/2023 8:23 AM, when the "shuffleListeners" test was added to CT by @samreid forhttps://github.com/phetsims/axon/issues/215.

```
reactants-products-and-leftovers : fuzz : unbuilt : shuffleListeners
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679393328551/reactants-products-and-leftovers/reactants-products-and-leftovers_en.html?continuousTest=%7B%22test%22%3A%5B%22reactants-products-and-leftovers%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22shuffleListeners%22%5D%2C%22snapshotName%22%3A%22snapshot-1679393328551%22%2C%22timestamp%22%3A1679399140991%7D&brand=phet&ea&fuzz&shuffleListeners&memoryLimit=1000
Query: brand=phet&ea&fuzz&shuffleListeners&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1679393328551/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:140:14)
at definedDependencies (DerivedProperty.ts:154:56)
at (TinyEmitter.ts:116:42)
at emit (ReadOnlyProperty.ts:312:22)
at _notifyListeners (ReadOnlyProperty.ts:263:13)
at unguardedSet (ReadOnlyProperty.ts:247:11)
at set (Property.ts:54:10)
at (PressListener.ts:745:4)
at apply (PhetioAction.ts:158:16)
id: Bayes Puppeteer
Snapshot from 3/21/2023, 6:08:48 AM
```

**Comment by zepumph** [comment]
Taking a look now.

**Comment by zepumph** [comment]
This one is a challenging case, in the stack there is nothing sim-specific. 

In the stack it goes fuzzing input-> PressListener -> Emitter code-> derivedProperty -> "the DerivedProperty is already disposed".

I can reproduce the assertion easier in the game screen.

I made commits, mostly to see if CT fixes itself. I don't feel too confident, but since it can take ~5 minutes to reproduce the bug, it is quite hard to have enough confidence to know if I do/don't need both of the flags. I'll check back on CT soon.

**Comment by zepumph** [comment]
It showed up on CT again.

**Comment by zepumph** [comment]
I don't see this on CT anymore, not in the last week or so.

**Comment by pixelzoom** [comment]
This issue is not blocking for 1.3 release https://github.com/phetsims/reactants-products-and-leftovers/issues/77.  But I'll try to take a look to see why `hasListenerOrderDependencies: true` is necessary.

**Comment by marlitas** [comment]
As of 9/22/23 I do not see the error in the last 40 columns of CT. Can this be closed? @pixelzoom and @zepumph

**Comment by zepumph** [comment]
I think this is still here, just hard to get to. That's how the shuffle tests work.
