### ISSUE TITLE
CT y should be a finite number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/reactants-products-and-leftovers#98]
```
reactants-products-and-leftovers : phet-io-fuzz : unbuilt
URL: http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/reactants-products-and-leftovers/reactants-products-and-leftovers_en.html?continuousTest=%7B%22test%22%3A%5B%22reactants-products-and-leftovers%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733950500334%22%2C%22timestamp%22%3A1733951446588%7D&ea&brand=phet-io&phetioStandalone&fuzz
ERROR: QUERY: ea&brand=phet-io&phetioStandalone&fuzz
Error: Assertion failed: y should be a finite number
STACK: window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/assert/js/assert.js:45:21
    at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/assert/js/assert.js:45:21)
    at assert (../../../../../../scenery/js/nodes/Node.ts:2458:16)
    at translate (../../../../../../scenery/js/nodes/Node.ts:3155:11)
    at setCenterY (../../../../../../scenery/js/nodes/Node.ts:3165:9)
    at titleAndButtonsParent (../../../../../../../reactants-products-and-leftovers/js/game/view/SettingsNode.ts:69:8)
    at callback (../../../../../axon/js/Multilink.ts:111:10)
    at listener (../../../../../axon/js/TinyEmitter.ts:213:6)
    at notifyLoop (../../../../../axon/js/TinyEmitter.ts:185:17)
    at emit (../../../../../axon/js/TinyStaticProperty.ts:56:9)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1570:30)
    at onAccessAttempt (../../../../../axon/js/TinyStaticProperty.ts:31:9)
    at get (../../../../../axon/js/TinyStaticProperty.ts:56:20)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1516:35)
    at onAccessAttempt (../../../../../axon/js/TinyStaticProperty.ts:31:9)
    at get (../../../../../axon/js/TinyStaticProperty.ts:56:20)
    at notifyListeners (../../../../../../scenery/js/nodes/Node.ts:1469:35)
    at validateBounds (../../../../../../scenery/js/nodes/Node.ts:1682:18)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1689:38)
    at watchedBoundsScan (../../../../../../scenery/js/nodes/Node.ts:1668:17)
    at validateWatchedBounds (../../../../../../scenery/js/display/Display.ts:568:19)
    at updateDisplay (../../../../../joist/js/Sim.ts:475:21)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../joist/js/Sim.ts:1078:30)
    at stepSimulation (../../../../../joist/js/Sim.ts:1068:11)
    at stepOneFrame (../../../../../joist/js/Sim.ts:1043:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
    at requestAnimationFrame (../../../../../joist/js/Sim.ts:1035:11)
====================
FULL LOG:
[URL] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733950500334%2Freactants-products-and-leftovers%2Freactants-products-and-leftovers_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22reactants-products-and-leftovers%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733950500334%22%2C%22timestamp%22%3A1733951446588%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733950500334%2Freactants-products-and-leftovers%2Freactants-products-and-leftovers_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22reactants-products-and-leftovers%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733950500334%22%2C%22timestamp%22%3A1733951446588%7D
[ATTACHED] 
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/reactants-products-and-leftovers/reactants-products-and-leftovers_en.html?continuousTest=%7B%22test%22%3A%5B%22reactants-products-and-leftovers%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733950500334%22%2C%22timestamp%22%3A1733951446588%7D&ea&brand=phet-io&phetioStandalone&fuzz
[CONSOLE] enabling assert
[LOADED] http://127.0.0.1/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1733950500334%2Freactants-products-and-leftovers%2Freactants-products-and-leftovers_en.html&simQueryParameters=ea%26brand%3Dphet-io%26phetioStandalone%26fuzz&testInfo=%7B%22test%22%3A%5B%22reactants-products-and-leftovers%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1733950500334%22%2C%22timestamp%22%3A1733951446588%7D
[CONSOLE] [JavaScript Warning: "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/chipper/dist/js/tambo/js/phetAudioContext.js" line: 11}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] [JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "http://127.0.0.1/continuous-testing/ct-snapshots/1733950500334/chipper/dist/js/scenery/js/util/Utils.js" line: 391}]
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed:  y should be a finite number
[CONSOLE] Debug info: {
  "seed": 0.19643169040959163,
  "currentScreenName": "SandwichesScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PhetMenu"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: y should be a finite number
[CONSOLE] Assertion failed:  y should be a finite number
[CONSOLE] Debug info: {
  "seed": 0.19643169040959163,
  "currentScreenName": "MoleculesScreen",
  "simTopLayer": [
    "BarrierRectangle",
    "PopupParentNode: PreferencesDialog"
  ]
}
[CONSOLE] continuous-test-error
[PAGE ERROR] Error: Assertion failed: y should be a finite number

id: "Sparky Node Firefox"
Snapshot from 12/11/2024, 1:55:00 PM
```

**Comment by pixelzoom** [comment]
This looks like a common-code problem.  I see a similar error in `watchedBoundsScan` reported by CT for balancing-chemical-equations, and molecule-polarity.  I'll ask on Slack#dev-public.

**Comment by pixelzoom** [comment]
CT started reporting this problem 5 minutes after https://github.com/phetsims/joist/commit/f8bb477362c6ba821859cc7d41b1fe60a7ec022e for https://github.com/phetsims/studio/issues/256 was pushed.  So assigning this issue to @zepumph.

**Comment by pixelzoom** [comment]
In https://phetsims.slack.com/archives/C6HPE0J91/p1733867193003619?thread_ts=1733867193.003619&cid=C6HPE0J91, @zepumph posted on 12/10 @ 2:46pm:

> Just like in https://phetsims.slack.com/archives/C6HPE0J91/p1733774411927849, I turned on a few more features for PhET-iO fuzzing for phetioFeatured elements in https://github.com/phetsims/phet-io/issues/2002. My guess is that overnight it is going to show some spots where changing featured Properties causes assertions. This will apply to all wrapper fuzzing (state/studio) and also the standalone "phet-io-fuzz" test.
> 
>
The most common error I'm seeing is about having a finite number when calculating bounds. This most likely means that all children in a container have an instrumented visibleProperty, and it crashes if you hide them all.

**Comment by pixelzoom** [comment]
I have no idea how to approach debugging this.  I also don't know whether it's a general problem, or something that needs to be addressed at the sim level. @zepumph can you clarify?

**Comment by pixelzoom** [comment]
It looks like a (complete?) list of sims encountering this fuzzing problem is in https://github.com/phetsims/phet-io/issues/2002#issuecomment-2536483826.  @KatieWoe @Nancy-Salpepi FYI.

**Comment by zepumph** [comment]
Toggling values of phetioFeatured visibleProperties in https://github.com/phetsims/phet-io/issues/2002 is showing this problem. I'll see if we are going to want a common code solution for when PhET-iO hides all children in a layout container.

**Comment by pixelzoom** [comment]
Discussed at 12/12/24 PhET-iO meeting.  @zepumph will handle this issue.

**Comment by zepumph** [comment]
Let's pick this up in https://github.com/phetsims/phet-io/issues/2003.

**Comment by zepumph** [comment]
This commit fixes the assertion, but I'm unsure that it is best. @pixelzoom, do you have any other ideas about how to solve this? I made an assumption that when the bounds are infinite, the previous location of the text is acceptable. It looked ok to me in testing, but please review and let me know what you think. You can reproduce this in studio by manually hiding each level selection button with the `visibleProperty`.

https://github.com/phetsims/reactants-products-and-leftovers/commit/295d950f297b27a802950d1a44b9d052ed20acac

![image](https://github.com/user-attachments/assets/0f6fe152-57fe-4028-98bc-4843001d9240)

**Comment by pixelzoom** [comment]
> This commit fixes the assertion, but I'm unsure that it is best. @pixelzoom, do you have any other ideas about how to solve this?

It would be preferrable if Panel always had finite bounds.

**Comment by pixelzoom** [comment]
So that developers don't need to be concerned with doing something like https://github.com/phetsims/reactants-products-and-leftovers/commit/295d950f297b27a802950d1a44b9d052ed20acac on a sim-by-sim basis for every Panel that is involved in layout.

**Comment by pixelzoom** [comment]
Ditto for other containers -- AccordionBox, etc.

**Comment by zepumph** [comment]
I'm not sure this is the desired default though. In Panel, this layout code is specifically designed to opt out and be invisible if the content is invisible:

https://github.com/phetsims/sun/blob/c785cc27eee1b8e4e68e70473907e6d3fbea802c/js/Panel.ts#L213-L220
